// Normally generated by `wrangler types` from wrangler.jsonc. This repo has no
// committed wrangler config — the deployed bindings come from the one Vite
// generates at dist/server/wrangler.json out of `localBindingConfig` in
// vite.config.ts — so this file is hand-maintained. Keep it in sync with that
// config and with worker/index.ts's Env interface.
declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
    MEDIA_BUCKET: R2Bucket;
    /** Bound to the `smart-cache` R2 bucket. Holds the rendered public
        documents worker/page-cache.ts stores under `page:` and the cached
        Supabase reads in app/lib/content.ts, events.ts and research.ts under
        `data:`. Declared optional because worker/index.ts falls back to
        vinext's in-memory handler when it is absent. */
    CACHE_BUCKET?: R2Bucket;
  }
}
