// Normally generated by `wrangler types` from wrangler.jsonc. This repo has no
// committed wrangler config (bindings live in the Cloudflare dashboard for the
// `smart` Worker instead), so this file is hand-maintained — keep it in sync
// with the dashboard's Bindings tab and worker/index.ts's Env interface.
declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
    MEDIA_BUCKET: R2Bucket;
    /** Bound to the `sst-cache` KV namespace. Backs the cached Supabase reads
        in app/lib/content.ts, events.ts and research.ts. Declared optional
        because worker/index.ts falls back to vinext's in-memory handler when
        it is absent, which is what local dev runs on. */
    VINEXT_CACHE?: KVNamespace;
  }
}
