"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "../../lib/supabase/browser";
import { IconArrowRight, IconCheck, IconFile, IconLayers, IconPlus, IconSearch, IconUser, IconUsers } from "./icons";

type Section = "overview" | "content" | "topics" | "events" | "contributors" | "people" | "messages";
type RecordItem = Record<string, unknown>;
type ContentItem = RecordItem & { id?: string; title?: string; status?: string; kind?: string; access_level?: string; topic_ids?: string[]; chapters?: { title: string; starts_at_seconds: number }[]; content_media?: Media[] };
type Media = { storage_path: string; public_url: string; kind: "image" | "document"; alt_text?: string; caption?: string };

const nav: { id: Section; label: string; icon: typeof IconLayers }[] = [
  { id: "overview", label: "Overview", icon: IconLayers }, { id: "content", label: "Content", icon: IconFile },
  { id: "topics", label: "Topics", icon: IconLayers }, { id: "events", label: "Events & webinars", icon: IconPlus },
  { id: "contributors", label: "Contributors", icon: IconUsers }, { id: "people", label: "People & roles", icon: IconUser },
  { id: "messages", label: "Contact inbox", icon: IconFile },
];

const emptyContent = (): ContentItem => ({ kind: "case_article", status: "published", access_level: "public", title: "", slug: "", summary: "", level: "Clinical education", topic_ids: [], chapters: [], content_media: [] });

function RichEditor({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const element = useRef<HTMLDivElement>(null);
  useEffect(() => { if (element.current && element.current.innerHTML !== value) element.current.innerHTML = value; }, [value]);
  function format(command: string) { element.current?.focus(); document.execCommand(command); onChange(element.current?.innerHTML ?? ""); }
  return <div className="admin-rich-editor"><div className="admin-rich-actions" aria-label="Text formatting"><button type="button" onClick={() => format("bold")}><b>B</b></button><button type="button" onClick={() => format("italic")}><i>I</i></button><button type="button" onClick={() => format("insertUnorderedList")}>List</button><button type="button" onClick={() => format("formatBlock")}>Heading</button></div><div ref={element} className="admin-rich-input" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" data-placeholder="Write the article introduction and supporting detail…" onInput={() => onChange(element.current?.innerHTML ?? "")} /></div>;
}

export default function AdminWorkspace() {
  const [active, setActive] = useState<Section>("overview");
  const [identity, setIdentity] = useState<RecordItem | null>(null);
  const [items, setItems] = useState<RecordItem[]>([]);
  const [topics, setTopics] = useState<RecordItem[]>([]);
  const [contributors, setContributors] = useState<RecordItem[]>([]);
  const [metrics, setMetrics] = useState<RecordItem>({});
  const [editing, setEditing] = useState<RecordItem | null>(null);
  const [notice, setNotice] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  async function authHeaders() {
    const { data } = await getSupabaseBrowserClient().auth.getSession();
    return { "Content-Type": "application/json", Authorization: `Bearer ${data.session?.access_token ?? ""}` };
  }
  async function request(resource: Section, init?: RequestInit) {
    const headers = await authHeaders();
    const response = await fetch(`/api/admin/${resource}`, { ...init, headers: { ...headers, ...(init?.headers ?? {}) } });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(result.error ?? "Something went wrong.");
    return result;
  }
  async function load(resource = active) {
    setLoading(true); setNotice("");
    try {
      const result = await request(resource);
      if (resource === "overview") { setIdentity(result.identity); setMetrics(result.metrics ?? {}); }
      else { setItems(result.data ?? []); if (resource === "content") { const topicResult = await request("topics"); const contributorResult = await request("contributors"); setTopics(topicResult.data ?? []); setContributors(contributorResult.data ?? []); } }
    } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load this area."); }
    finally { setLoading(false); }
  }
  // Reload only when the selected workspace section changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [active]);

  const filtered = useMemo(() => items.filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())), [items, search]);
  function startNew() {
    if (active === "content") setEditing(emptyContent());
    else if (active === "topics") setEditing({ name: "", slug: "", description: "", sort_order: 0 });
    else if (active === "events") setEditing({ title: "", slug: "", event_type: "Webinar", format: "online", status: "published" });
    else if (active === "contributors") setEditing({ display_name: "", credentials: "", role_title: "", group_name: "", biography: "", published: true, sort_order: 0 });
    else setEditing(null);
  }
  async function save(value: RecordItem) {
    try {
      await request(active, { method: "POST", body: JSON.stringify(value) }); setNotice("Saved. The public site will reflect published changes without a code release."); setEditing(null); await load();
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save this item."); }
  }
  async function remove(item: RecordItem) {
    if (!window.confirm(`Delete “${String(item.title ?? item.name ?? item.display_name ?? "this item")}”? This cannot be undone.`)) return;
    try { const headers = await authHeaders(); const response = await fetch(`/api/admin/${active}?id=${encodeURIComponent(String(item.id))}`, { method: "DELETE", headers }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setNotice("Deleted."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not delete this item."); }
  }
  async function signOut() { await getSupabaseBrowserClient().auth.signOut(); window.location.assign("/en/sign-in"); }

  if (!identity && !loading && notice) return <main className="admin-access"><span className="admin-kicker">Smart Surgical Team</span><h1>Admin access required</h1><p>{notice}</p><Link className="btn btn-primary" href="/en/sign-in">Sign in</Link></main>;
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" href="/en"><span>SST</span><b>Admin</b></Link><div className="admin-owner"><span>{String(identity?.full_name ?? identity?.name ?? "Owner").split(" ").slice(0, 2).map((part) => part[0]).join("")}</span><div><b>{String(identity?.full_name ?? identity?.name ?? "Smart Surgical Team")}</b><small>{String(identity?.role ?? "owner").replace(/_/g, " ")}</small></div></div><nav aria-label="Admin sections">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={active === id ? "is-active" : ""} type="button" onClick={() => { setActive(id); setEditing(null); setSearch(""); }}><Icon size={18}/>{label}</button>)}</nav><button className="admin-signout" type="button" onClick={signOut}>Sign out</button></aside><section className="admin-main"><header className="admin-topbar"><div><span className="admin-kicker">Content operations</span><h1>{nav.find((item) => item.id === active)?.label}</h1></div>{["content", "topics", "events", "contributors"].includes(active) && <button className="btn btn-primary" type="button" onClick={startNew}><IconPlus size={17}/> Add {active === "content" ? "content" : active === "events" ? "event" : active.slice(0, -1)}</button>}</header>{notice && <p className="admin-notice" role="status"><IconCheck size={17}/>{notice}</p>}{loading ? <div className="admin-loading">Loading workspace…</div> : <>{active === "overview" ? <Overview metrics={metrics} setActive={setActive}/> : editing ? <Editor section={active} value={editing} topics={topics} contributors={contributors} onCancel={() => setEditing(null)} onSave={save}/> : <List section={active} items={filtered} search={search} setSearch={setSearch} onEdit={setEditing} onDelete={remove}/>}</>}</section></main>;
}

function Overview({ metrics, setActive }: { metrics: RecordItem; setActive: (section: Section) => void }) {
  const cards: { key: string; label: string; section: Section }[] = [{ key: "published", label: "Published items", section: "content" }, { key: "drafts", label: "Drafts & unpublishing", section: "content" }, { key: "events", label: "Published events", section: "events" }, { key: "contributors", label: "Contributors", section: "contributors" }, { key: "members", label: "Members", section: "people" }, { key: "messages", label: "Inbox messages", section: "messages" }];
  return <div className="admin-overview"><section className="admin-welcome"><div><span className="admin-kicker">Control room</span><h2>Keep the platform current, carefully.</h2><p>Publish case articles, update the team, and keep events and learning material accurate from one place.</p></div><button className="btn btn-primary" type="button" onClick={() => setActive("content")}>Create a case article <IconArrowRight size={17}/></button></section><div className="admin-metric-grid">{cards.map((card) => <button type="button" onClick={() => setActive(card.section)} key={card.key}><strong>{String(metrics[card.key] ?? 0)}</strong><span>{card.label}</span><IconArrowRight size={16}/></button>)}</div><section className="admin-safety"><h2>Clinical publishing reminder</h2><p>Only publish material that has been de-identified, consented, and approved by the team. Articles are public unless you select “Site users only” in the content editor.</p></section></div>;
}

function List({ section, items, search, setSearch, onEdit, onDelete }: { section: Section; items: RecordItem[]; search: string; setSearch: (value: string) => void; onEdit: (item: RecordItem) => void; onDelete: (item: RecordItem) => void }) {
  const isMessages = section === "messages";
  return <div className="admin-list"><div className="admin-list-controls"><label><IconSearch size={17}/><span className="visually-hidden">Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${section.replace("people", "people and roles")}…`}/></label><span>{items.length} item{items.length === 1 ? "" : "s"}</span></div>{items.length ? <div className="admin-table">{items.map((item) => <article key={String(item.id)}><div className="admin-item-main"><span className={`admin-status is-${String(item.status ?? item.role ?? "default")}`}>{String(item.status ?? item.role ?? (item.published === false ? "hidden" : "active")).replace(/_/g, " ")}</span><h2>{String(item.title ?? item.name ?? item.display_name ?? item.email ?? "Untitled")}</h2><p>{String(item.summary ?? item.description ?? item.message ?? item.credentials ?? item.role_title ?? item.email ?? "No additional detail.")}</p></div><div className="admin-item-meta">{section === "content" && <><span>{String(item.kind ?? "article").replace(/_/g, " ")}</span><span>{String(item.access_level === "members_only" ? "Site users only" : "Public")}</span></>}{section === "events" && <span>{item.starts_at ? new Date(String(item.starts_at)).toLocaleDateString() : "Date to be confirmed"}</span>}{section === "people" && <span>{String(item.email ?? "")}</span>}{!isMessages && <div><button type="button" onClick={() => onEdit(item)}>Edit</button>{section !== "people" && <button className="admin-delete" type="button" onClick={() => onDelete(item)}>Delete</button>}</div>}</div></article>)}</div> : <div className="admin-empty"><IconFile size={23}/><h2>Nothing here yet</h2><p>Create the first item when you are ready.</p></div>}</div>;
}

function Editor({ section, value, topics, contributors, onCancel, onSave }: { section: Section; value: RecordItem; topics: RecordItem[]; contributors: RecordItem[]; onCancel: () => void; onSave: (value: RecordItem) => void }) {
  const [form, setForm] = useState<RecordItem>(() => ({ ...value, topic_ids: Array.isArray(value.content_topics) ? value.content_topics.flatMap((row) => typeof row === "object" && row ? [String((row as RecordItem).topic_id)] : []) : value.topic_ids ?? [], chapters: Array.isArray(value.content_chapters) ? value.content_chapters : value.chapters ?? [], content_media: Array.isArray(value.content_media) ? value.content_media : [] }));
  const [uploading, setUploading] = useState(false);
  const set = (key: string, next: unknown) => setForm((current) => ({ ...current, [key]: next }));
  async function upload(file: File) { setUploading(true); try { const { data } = await getSupabaseBrowserClient().auth.getSession(); const body = new FormData(); body.append("file", file); const response = await fetch("/api/admin/upload", { method: "POST", headers: { Authorization: `Bearer ${data.session?.access_token ?? ""}` }, body }); const result = await response.json(); if (!response.ok) throw new Error(result.error); set("content_media", [...(form.content_media as Media[]), { storage_path: result.path, public_url: result.publicUrl, kind: result.kind, alt_text: "", caption: "" }]); } finally { setUploading(false); } }
  function submit(event: FormEvent) { event.preventDefault(); onSave({ ...form, media: form.content_media }); }
  if (section === "content") return <form className="admin-editor" onSubmit={submit}><EditorHead title={form.id ? "Edit content" : "New content"} onCancel={onCancel}/><div className="admin-editor-grid"><section><Field label="Title" value={form.title} onChange={(value) => set("title", value)} required/><Field label="URL slug" hint="Leave this blank to generate it from the title." value={form.slug} onChange={(value) => set("slug", value)}/><Field label="Card summary" type="textarea" value={form.summary} onChange={(value) => set("summary", value)} required/><div className="admin-field-grid"><Select label="Format" value={form.kind} onChange={(value) => set("kind", value)} options={[['case_article','Case article'],['video','Video lesson'],['webinar_recording','Recorded webinar'],['poster','E-poster']]}/><Select label="Publishing" value={form.status} onChange={(value) => set("status", value)} options={[['published','Published now'],['draft','Save as draft'],['archived','Unpublish / archive'],['scheduled','Schedule']]}/></div>{form.status === "scheduled" && <Field label="Publish on" type="datetime-local" value={form.scheduled_for} onChange={(value) => set("scheduled_for", value)}/>}<div className="admin-field-grid"><Select label="Visibility" value={form.access_level} onChange={(value) => set("access_level", value)} options={[['public','Public'],['members_only','Site users only']]}/><Select label="Contributor" value={form.contributor_id} onChange={(value) => set("contributor_id", value)} options={[["", "Smart Surgical Team"], ...contributors.map((person) => [String(person.id), String(person.display_name)])]}/></div><label className="admin-label">Topics<select multiple value={(form.topic_ids as string[]) ?? []} onChange={(event) => set("topic_ids", Array.from(event.target.selectedOptions).map((option) => option.value))}>{topics.map((topic) => <option value={String(topic.id)} key={String(topic.id)}>{String(topic.name)}</option>)}</select><small>Choose every relevant topic. Hold Ctrl/Cmd to select more than one.</small></label><div className="admin-field-grid"><Field label="Video URL (optional)" type="url" value={form.video_url} onChange={(value) => set("video_url", value)}/><Field label="Reading time (minutes)" type="number" value={form.reading_minutes} onChange={(value) => set("reading_minutes", value)}/></div><Field label="Clinical level" value={form.level} onChange={(value) => set("level", value)}/><label className="admin-label">Article body<RichEditor value={String(form.body_html ?? "")} onChange={(value) => set("body_html", value)}/></label><CaseFields form={form} set={set}/></section><aside><MediaManager media={(form.content_media as Media[]) ?? []} setMedia={(media) => set("content_media", media)} upload={upload} uploading={uploading}/><Chapters chapters={(form.chapters as { title: string; starts_at_seconds: number }[]) ?? []} setChapters={(chapters) => set("chapters", chapters)}/></aside></div><EditorFoot onCancel={onCancel}/></form>;
  if (section === "topics") return <SimpleEditor title={form.id ? "Edit topic" : "New topic"} fields={[['name','Topic name'],['slug','URL slug'],['description','Description'],['sort_order','Display order']]} form={form} set={set} onCancel={onCancel} onSave={submit} topics={topics}/>;
  if (section === "events") return <SimpleEditor title={form.id ? "Edit event" : "New event or webinar"} fields={[['title','Title'],['slug','URL slug'],['summary','Summary'],['event_type','Type'],['topic','Topic'],['format','Format'],['status','Status'],['starts_at','Starts at'],['ends_at','Ends at'],['location','Location'],['image_url','Image URL'],['official_url','Official URL'],['registration_url','Registration URL'],['programme_url','Programme URL']]} form={form} set={set} onCancel={onCancel} onSave={submit}/>;
  if (section === "people") return <form className="admin-editor admin-simple-editor" onSubmit={submit}><EditorHead title={`Manage ${String(form.full_name ?? form.email)}`} onCancel={onCancel}/><div className="admin-simple-fields"><Field label="Email" value={form.email} onChange={() => {}}/><Select label="Platform role" value={form.role} onChange={(value) => set("role", value)} options={[['owner','Owner'],['content_manager','Content manager'],['editor','Editor'],['contributor','Contributor'],['member','Member']]}/><p className="admin-role-note">Only the Owner can change roles. The designated Owner account cannot be downgraded here.</p></div><EditorFoot onCancel={onCancel}/></form>;
  return <SimpleEditor title={form.id ? "Edit contributor" : "New contributor"} fields={[['display_name','Full name'],['credentials','Credentials'],['role_title','Role'],['group_name','Team group'],['photo_url','Portrait URL'],['biography','Biography'],['sort_order','Display order']]} form={form} set={set} onCancel={onCancel} onSave={submit}/>;
}

function CaseFields({ form, set }: { form: RecordItem; set: (key: string, value: unknown) => void }) { const fields = [['case_presentation','Patient presentation'],['case_imaging','Imaging & workup'],['case_procedure','Surgical management'],['case_histopathology','Histopathology'],['case_outcome','Outcome & follow-up']]; return <section className="admin-case-fields"><h2>Structured case record</h2><p>Every section is optional. Add only reviewed, de-identified material.</p>{fields.map(([key, label]) => <Field key={key} label={label} type="textarea" value={form[key]} onChange={(value) => set(key, value)}/>)}</section>; }
function MediaManager({ media, setMedia, upload, uploading }: { media: Media[]; setMedia: (value: Media[]) => void; upload: (file: File) => void; uploading: boolean }) { return <section className="admin-media"><h2>Images & PDFs</h2><p>Add a cover image, in-article images, or a downloadable PDF. Video is optional and entered in the main form.</p><label className="admin-upload"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0])}/><IconPlus size={18}/>{uploading ? "Uploading…" : "Upload file"}</label>{media.map((item, index) => <div className="admin-media-item" key={item.storage_path}><span>{item.kind === "image" ? "Image" : "PDF"}</span><input value={item.alt_text ?? ""} onChange={(event) => setMedia(media.map((entry, position) => position === index ? { ...entry, alt_text: event.target.value } : entry))} placeholder="Alt text / file description"/><button type="button" onClick={() => setMedia(media.filter((_, position) => position !== index))}>Remove</button></div>)}</section>; }
function Chapters({ chapters, setChapters }: { chapters: { title: string; starts_at_seconds: number }[]; setChapters: (chapters: { title: string; starts_at_seconds: number }[]) => void }) { return <section className="admin-chapters"><div><h2>Video chapters</h2><button type="button" onClick={() => setChapters([...chapters, { title: "", starts_at_seconds: 0 }])}>Add chapter</button></div>{chapters.length ? chapters.map((chapter, index) => <div className="admin-chapter" key={index}><input value={chapter.title} onChange={(event) => setChapters(chapters.map((entry, position) => position === index ? { ...entry, title: event.target.value } : entry))} placeholder="Chapter title"/><input type="number" value={chapter.starts_at_seconds} onChange={(event) => setChapters(chapters.map((entry, position) => position === index ? { ...entry, starts_at_seconds: Number(event.target.value) } : entry))} aria-label="Start time in seconds"/><button type="button" onClick={() => setChapters(chapters.filter((_, position) => position !== index))}>×</button></div>) : <p>No chapters added.</p>}</section>; }
function EditorHead({ title, onCancel }: { title: string; onCancel: () => void }) { return <div className="admin-editor-head"><div><span className="admin-kicker">Content editor</span><h2>{title}</h2></div><button type="button" className="admin-close" onClick={onCancel}>Close</button></div>; }
function EditorFoot({ onCancel }: { onCancel: () => void }) { return <div className="admin-editor-foot"><button className="btn btn-primary" type="submit">Save changes <IconArrowRight size={17}/></button><button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button></div>; }
function Field({ label, value, onChange, type = "text", hint, required = false }: { label: string; value: unknown; onChange: (value: string) => void; type?: string; hint?: string; required?: boolean }) { return <label className="admin-label">{label}{type === "textarea" ? <textarea value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} required={required}/> : <input type={type} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} required={required}/>} {hint && <small>{hint}</small>}</label>; }
function Select({ label, value, onChange, options }: { label: string; value: unknown; onChange: (value: string) => void; options: string[][] }) { return <label className="admin-label">{label}<select value={String(value ?? "")} onChange={(event) => onChange(event.target.value)}>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
function SimpleEditor({ title, fields, form, set, onCancel, onSave, topics }: { title: string; fields: string[][]; form: RecordItem; set: (key: string, value: unknown) => void; onCancel: () => void; onSave: (event: FormEvent) => void; topics?: RecordItem[] }) { return <form className="admin-editor admin-simple-editor" onSubmit={onSave}><EditorHead title={title} onCancel={onCancel}/><div className="admin-simple-fields">{fields.map(([key, label]) => <Field key={key} label={label} type={key === "summary" || key === "description" || key === "biography" ? "textarea" : key.includes("_at") ? "datetime-local" : key.includes("url") ? "url" : key === "sort_order" ? "number" : "text"} value={form[key]} onChange={(value) => set(key, value)}/>) }{topics && <label className="admin-label">Parent topic<select value={String(form.parent_id ?? "")} onChange={(event) => set("parent_id", event.target.value)}><option value="">No parent (top-level topic)</option>{topics.filter((topic) => topic.id !== form.id).map((topic) => <option value={String(topic.id)} key={String(topic.id)}>{String(topic.name)}</option>)}</select></label>}</div><EditorFoot onCancel={onCancel}/></form>; }
